# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_scMAGeCK_rcpp_hello_world`)
}

call_rra <- function(RRA_parameters) {
    .Call(`_scMAGeCK_call_rra`, RRA_parameters)
}

